version: "3.1"

services:
  bitbucketserver:
    image: atlassian/bitbucket-server:latest
    container_name: bitbucket
    restart: always
    depends_on:
      - sqlserver
    ports:
      - 7990:7990
      - 7999:7999
    environment:
      ELASTICSEARCH_ENABLED: "false"
    volumes:
      - bitbucket-vol:/var/atlassian/application-data/bitbucket

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: "0:0"
    container_name: sqlserver2019
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01.
      MSSQL_PID: Express
    volumes:
      - sqlserver-vol:/var/opt/mssql

volumes:
  bitbucket-vol:
  sqlserver-vol:
